[".config/alacritty/catppuccin-mocha.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"

[".config/btop/themes/catppuccin_mocha.theme"]
type = "file"
url = "https://github.com/catppuccin/btop/raw/refs/heads/main/themes/catppuccin_mocha.theme"
refreshPeriod = "168h"

[".config/catppuccin/delta/catppuccin.gitconfig"]
type = "file"
url = "https://github.com/catppuccin/delta/raw/refs/heads/main/catppuccin.gitconfig"
refreshPeriod = "168h"

[".config/gitui/theme.ron"]
type = "file"
url = "https://github.com/catppuccin/gitui/raw/refs/heads/main/themes/catppuccin-mocha.ron"
refreshPeriod = "168h"

[".config/yazi/theme.toml"]
type = "file"
url = "https://github.com/catppuccin/yazi/raw/refs/heads/main/themes/mocha/catppuccin-mocha-blue.toml"
refreshPeriod = "168h"
