# man 5 alacritty

import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
dynamic_padding = true     # Spread additional padding evenly around the terminal content.
decorations = "buttonless"
opacity = 0.7
blur = true
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[font]
size = 16
builtin_box_drawing = true

[font.normal]
# family = "FiraCode Nerd Font"
# family = "MonaspiceNe Nerd Font"
family = "InputMono Nerd Font"
style = "Regular"

[font.bold]
family = "InputMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "InputMonoIta Nerd Font"
style = "Bold"

[font.italic]
family = "InputMono Nerd Font"
style = "Italic"

[selection]
save_to_clipboard = true # selected text will be copied to the primary clipboard.

[cursor]
style = { shape = "Underline", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true
thickness = 0.25

[mouse]
hide_when_typing = true # the cursor is temporarily hidden when typing
bindings = [
  { mouse = "Right", action = "ExpandSelection" },
  { mouse = "Middle", mode = "~Vi", action = "PasteSelection" },
]

[hints]
alphabet = "hutenosadigpc.r,l;" # Keys used for the hint labels.
# enabled = [
#   { command = "xdg-open", hyperlinks = true, post_processing = true, persist = false, mouse.enabled = true, binding = { key = "U", mods = "Control|Shift" }, regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+" }
# ]

[keyboard]
bindings = [
  { key = "Return", mods = "Control", mode = "~Vi", action = "SpawnNewInstance" },
]
