(("doom" . ((user-emacs-directory . "~/.local/share/doomemacs")
            (server-name          . "doom")
            (env . (("DOOMDIR"    . "~/.config/doom")))
            ))
 ("spacemacs" . ((user-emacs-directory  . "~/.local/share/spacemacs")
                 (server-name           . "spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.config/spacemacs")))
                 ))
  )
