interactive = true
progress = true
verbose = true

[diff]
command = "delta"
pager = "delta"

[edit]
apply = false
watch = false

[git]
autoAdd = true
autoCommit = true
# autoPush = true

[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
# args = [
#   "-d",
#   "-o2",
#   "{{ .Destination }}",
#   "{{ .Target }}",
#   "-O",
#   "{{ .Source }}",
# ]
